#!/bin/sh

baseDir=$1

mkdir -p features plugins
mv $baseDir/about* .
mv $baseDir/configuration/ .
mv $baseDir/eclipse{,.ini} .
mv $baseDir/epl-v10.html .
mv $baseDir/notice.html .
mv $baseDir/readme/ .
mv $baseDir/features/org.eclipse.platform_* features
mv $baseDir/features/org.eclipse.help_* features
mv $baseDir/features/org.eclipse.cvs_* features
mv $baseDir/plugins/org.eclipse.cvs_* plugins
mv $baseDir/plugins/org.eclipse.team.cvs.core_* plugins
mv $baseDir/plugins/org.eclipse.team.cvs.ssh_* plugins
mv $baseDir/plugins/org.eclipse.team.cvs.ssh2_* plugins
mv $baseDir/plugins/org.eclipse.team.cvs.ui_* plugins
mv $baseDir/features/org.eclipse.equinox.p2.user.ui_* features
mv $baseDir/plugins/*linux* plugins
mv $baseDir/plugins/com.jcraft.jsch_* plugins
mv $baseDir/plugins/org.eclipse.compare_* plugins
mv $baseDir/plugins/org.eclipse.compare.core_* plugins
mv $baseDir/plugins/org.eclipse.core.boot_* plugins
mv $baseDir/plugins/org.eclipse.core.filebuffers_* plugins
mv $baseDir/plugins/org.eclipse.core.filesystem_* plugins
mv $baseDir/plugins/org.eclipse.core.net_* plugins
mv $baseDir/plugins/org.eclipse.core.resources_* plugins
mv $baseDir/plugins/org.eclipse.core.resources.compatibility_* plugins
mv $baseDir/plugins/org.eclipse.osgi.util_* plugins
mv $baseDir/plugins/org.eclipse.debug.core_* plugins
mv $baseDir/plugins/org.eclipse.debug.ui_* plugins
mv $baseDir/plugins/org.eclipse.help.appserver_* plugins
mv $baseDir/plugins/org.eclipse.ltk.core.refactoring_* plugins
mv $baseDir/plugins/org.eclipse.ltk.ui.refactoring_* plugins
mv $baseDir/plugins/org.eclipse.platform_* plugins
mv $baseDir/plugins/org.eclipse.platform.doc.user_* plugins
mv $baseDir/plugins/org.eclipse.search_* plugins
mv $baseDir/plugins/org.eclipse.team.core_* plugins
mv $baseDir/plugins/org.eclipse.team.ui_* plugins
mv $baseDir/plugins/org.eclipse.text_* plugins
mv $baseDir/plugins/org.eclipse.jface.text_* plugins
mv $baseDir/plugins/org.eclipse.jsch.core_* plugins
mv $baseDir/plugins/org.eclipse.jsch.ui_* plugins
mv $baseDir/plugins/org.eclipse.ui.console_* plugins
mv $baseDir/plugins/org.eclipse.ui.presentations.r21_* plugins
mv $baseDir/plugins/org.eclipse.ui.intro_* plugins
mv $baseDir/plugins/org.eclipse.ui.intro.universal_* plugins
mv $baseDir/plugins/org.eclipse.ui.cheatsheets_* plugins
mv $baseDir/plugins/org.eclipse.ui.browser_* plugins
mv $baseDir/plugins/org.eclipse.ui.navigator_* plugins
mv $baseDir/plugins/org.eclipse.ui.navigator.resources_* plugins
mv $baseDir/plugins/org.eclipse.ui.net_* plugins
mv $baseDir/plugins/org.eclipse.ui.workbench.texteditor_* plugins
mv $baseDir/plugins/org.eclipse.ui.views_* plugins
mv $baseDir/plugins/org.eclipse.ui.editors_* plugins
mv $baseDir/plugins/org.eclipse.ui.externaltools_* plugins
mv $baseDir/plugins/org.eclipse.ui.ide_* plugins
mv $baseDir/plugins/org.eclipse.ui.ide.application_* plugins
mv $baseDir/plugins/org.eclipse.update.core_* plugins
mv $baseDir/plugins/org.eclipse.update.scheduler_* plugins
mv $baseDir/plugins/org.eclipse.update.ui_* plugins
mv $baseDir/plugins/org.eclipse.ui.workbench.compatibility_* plugins
mv $baseDir/plugins/org.eclipse.ui.views.properties.tabbed_* plugins
mv $baseDir/plugins/org.eclipse.equinox.security_* plugins
mv $baseDir/plugins/org.eclipse.equinox.security.ui_* plugins
mv $baseDir/features/org.eclipse.rcp_* features
mv $baseDir/plugins/com.ibm.icu_* plugins
mv $baseDir/plugins/org.eclipse.core.commands_* plugins
mv $baseDir/plugins/org.eclipse.core.databinding_* plugins
mv $baseDir/plugins/org.eclipse.core.databinding.beans_* plugins
mv $baseDir/plugins/org.eclipse.core.databinding.observable_* plugins
mv $baseDir/plugins/org.eclipse.core.databinding.property_* plugins
mv $baseDir/plugins/org.eclipse.core.jobs_* plugins
mv $baseDir/plugins/org.eclipse.core.expressions_* plugins
mv $baseDir/plugins/org.eclipse.core.runtime_* plugins
mv $baseDir/plugins/org.eclipse.core.runtime.compatibility.auth_* plugins
mv $baseDir/plugins/org.eclipse.osgi_* plugins
mv $baseDir/plugins/org.eclipse.help_* plugins
mv $baseDir/plugins/org.eclipse.swt_* plugins
mv $baseDir/plugins/org.eclipse.jface_* plugins
mv $baseDir/plugins/org.eclipse.jface.databinding_* plugins
mv $baseDir/plugins/org.eclipse.ui_* plugins
mv $baseDir/plugins/org.eclipse.ui.workbench_* plugins
mv $baseDir/plugins/org.eclipse.update.configurator_* plugins
mv $baseDir/plugins/org.eclipse.equinox.simpleconfigurator_* plugins
mv $baseDir/plugins/org.eclipse.rcp_* plugins
mv $baseDir/plugins/org.eclipse.core.contenttype_* plugins
mv $baseDir/plugins/org.eclipse.equinox.app_* plugins
mv $baseDir/plugins/org.eclipse.equinox.common_* plugins
mv $baseDir/plugins/org.eclipse.equinox.ds_* plugins
mv $baseDir/plugins/org.eclipse.equinox.initializer_* plugins
mv $baseDir/plugins/org.eclipse.equinox.preferences_* plugins
mv $baseDir/plugins/org.eclipse.equinox.registry_* plugins
mv $baseDir/plugins/org.eclipse.equinox.util_* plugins
mv $baseDir/plugins/org.eclipse.equinox.launcher_* plugins
mv $baseDir/plugins/org.eclipse.core.runtime.compatibility.registry_* plugins
mv $baseDir/plugins/org.eclipse.core.variables_* plugins
mv $baseDir/plugins/javax.servlet_* plugins
mv $baseDir/plugins/javax.servlet.jsp_* plugins
mv $baseDir/plugins/org.apache.ant_* plugins
mv $baseDir/plugins/org.apache.commons.codec_* plugins
mv $baseDir/plugins/org.apache.commons.el_* plugins
mv $baseDir/plugins/org.apache.commons.logging_* plugins
mv $baseDir/plugins/org.apache.commons.httpclient_* plugins
mv $baseDir/plugins/org.apache.jasper_* plugins
mv $baseDir/plugins/org.apache.lucene_* plugins
mv $baseDir/plugins/org.apache.lucene.analysis_* plugins
mv $baseDir/plugins/org.eclipse.ant.core_* plugins
mv $baseDir/plugins/org.eclipse.core.runtime.compatibility_* plugins
mv $baseDir/plugins/org.eclipse.ecf_* plugins
mv $baseDir/plugins/org.eclipse.ecf.filetransfer_* plugins
mv $baseDir/plugins/org.eclipse.ecf.identity_* plugins
mv $baseDir/plugins/org.eclipse.ecf.provider.filetransfer_* plugins
mv $baseDir/plugins/org.eclipse.ecf.provider.filetransfer.httpclient_* plugins
mv $baseDir/plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl_* plugins
mv $baseDir/plugins/org.eclipse.ecf.provider.filetransfer.ssl_* plugins
mv $baseDir/plugins/org.eclipse.ecf.ssl_* plugins
mv $baseDir/plugins/org.eclipse.equinox.frameworkadmin_* plugins
mv $baseDir/plugins/org.eclipse.equinox.frameworkadmin.equinox_* plugins
mv $baseDir/plugins/org.eclipse.equinox.http.jetty_* plugins
mv $baseDir/plugins/org.eclipse.equinox.http.registry_* plugins
mv $baseDir/plugins/org.eclipse.equinox.http.servlet_* plugins
mv $baseDir/plugins/org.eclipse.equinox.jsp.jasper_* plugins
mv $baseDir/plugins/org.eclipse.equinox.jsp.jasper.registry_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.artifact.repository_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.console_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.core_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.director_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.director.app_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.directorywatcher_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.engine_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.exemplarysetup_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.extensionlocation_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.garbagecollector_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.jarprocessor_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.metadata_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.metadata.generator_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.metadata.repository_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.publisher_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.repository_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.repository.tools_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.reconciler.dropins_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.touchpoint.eclipse_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.touchpoint.natives_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.ui_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.ui.sdk_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.ui.sdk.scheduler_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.updatechecker_* plugins
mv $baseDir/plugins/org.eclipse.equinox.p2.updatesite_* plugins
mv $baseDir/plugins/org.eclipse.equinox.simpleconfigurator.manipulator_* plugins
mv $baseDir/plugins/org.eclipse.help.base_* plugins
mv $baseDir/plugins/org.eclipse.help.ui_* plugins
mv $baseDir/plugins/org.eclipse.help.webapp_* plugins
mv $baseDir/plugins/org.eclipse.osgi.services_* plugins
mv $baseDir/plugins/org.eclipse.ui.forms_* plugins
mv $baseDir/plugins/org.mortbay.jetty.util_* plugins
mv $baseDir/plugins/org.mortbay.jetty.server_* plugins
mv $baseDir/plugins/org.sat4j.core_* plugins
mv $baseDir/plugins/org.sat4j.pb_* plugins
sed -i 's/org.eclipse.sdk.ide/org.eclipse.platform.ide/' configuration/config.ini
